Dibujado del fondo
uqbar-project/wollok-run-client pull request #16
Opened 2020-09-04 19:53 UTC by tfloxolodeiro

Resolves #4 
* Ahora se dibuja el boardGround, de forma tal que ocupe toda la pantalla del juego.
* La imagen default del ground ahora se esta poniendo a la fuerza entre las imágenes del juego. Habría que ver de mejorar esto e incluir las otras imagenes default pero esto nos permite probar varios juegos que antes rompían porque no teníamos el ground default.
* Tambien se cambio el retorno de la función `wKeyCode` ante una tecla no contemplada de undefined a string vacio porque explotaba.
* Se cambio la dependencia de ts para que apunte a master.
* En varios lugares donde se usan los locals se actualizo la forma de acceso de `locals[name]` a `locals.get(name)` para que ande con el master de ts.

2020-09-04 19:59 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +}
Acá directamente use un try catch porque este es el único atributo del game que podría no estar.

2020-09-06 09:33 UTC, PalumboN requested changes
Dejé algunos comments!

2020-09-06 09:33 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +}
Mmmm este `try catch` no me convence mucho, preferiría tener un if.  Creo que lo mejor sería que los `...FieldValue` retornen `undefined` cuando cuando no existe el atributo, o buscar alguna alternativa de ese estilo.

2020-09-06 09:33 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +  return ''
Acá habría que dejar un comentario?? :thinking:

2020-09-06 09:33 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +  }
Acá podría darse el caso que `imgs[boardGroundPath]` de undefined, no? Onda si pongo mal el nombre del fondo (sí, un caso de mierda, pero lo pienso para ya atajarlo).

2020-09-06 09:33 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +    imgs['ground.png'] = sketch.loadImage('https://raw.githubusercontent.com/uqbar-project/wollok/dev/org.uqbar.project.wollok.game/assets/ground.png')
Estas definiciones las sacaría del código, y agregaría todas las imágenes que faltan. Se podría tener algo como:
```typescript
const defaultImgs = [
  ['ground.png', 'https://raw.githubusercontent.com/uqbar-project/wollok/dev/org.uqbar.project.wollok.game/assets/ground.png'],
  ...
]
```

Y después hacer
```typescript
defaultImgs.forEach(([path, url]: string[]) => { img[path] = sketch.loadImage(url) })
```

2020-09-07 14:40 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +}
Trate de hacer que los `FieldValue` puedan retornar undefined, pero no pude lograr que las funciones hagan el assert del tipo del innerValue y que al mismo tiempo puedan devolver undefined sin que el tipado explote. Ahora pushie una alternativa creo que menos peor con un if en esta función, pero si hay alguna forma simple de hacer que los `FieldValue` puedan devolver undefined creo que estaría mejor.

2020-09-07 14:40 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +  return ''
Ahí deje un comentario que creo que se podría mejorar, pero no se me ocurrió uno mejor. De paso me pareció apropiado explicitar el tipado de la función para que siempre devuelva string.

2020-09-07 14:49 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +  }
Tal vez se podría reemplazar el imgs[path] por una función `imageFromPath` que devuelva la imagen en el path y ante un path desconocido devuelva la imagen default de wollok?. De paso esto también solucionaría #15.

2020-09-07 20:42 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +  }
Tuve varios problemas al tratar de mantener la alternativa de que el boardGround sea una imagen como el resto pero resizeada. Principalmente que hacerle directamente el resize al boardground seria conflictivo si existe algun objeto con la misma imagen que el boardground, lo cual podria ocurrir si el boardground tiene un path que no existe y hay tambien algún objeto con un path inexistente (ambos serian la imagen default de wollok y ambos quedarian cambiados de tamaño).

2020-09-07 20:57 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
> +    imgs['ground.png'] = sketch.loadImage('https://raw.githubusercontent.com/uqbar-project/wollok/dev/org.uqbar.project.wollok.game/assets/ground.png')
Termine poniendo los path default en el GameProject para que esten en el mismo lugar que las paths normales. Tal vez se podria hacer que los path default esten metidos en el imagePaths y no tengan un tratamiento especial cuando se cargan las imagenes, pero creo que se tendrian que cambiar varias cosas para hacerlo.

2020-09-10 19:43 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +    imgs['ground.png'] = sketch.loadImage('https://raw.githubusercontent.com/uqbar-project/wollok/dev/org.uqbar.project.wollok.game/assets/ground.png')
Excelente, sí habría que pre-calcular los paths de todas las imágenes y no necesitar el `assetSource`.

2020-09-10 19:45 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +    return undefined
```suggestion
  return gameInstanceField(evaluation, 'boardGround') && stringGameFieldValue(evaluation, 'boardGround')
```

2020-09-10 19:50 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +    return undefined
Habría que probarlo (?

2020-09-10 19:50 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +  return matrix
Esta variable no sería necesario entonces.

2020-09-10 19:50 UTC, PalumboN commented on src/components/game/Sketch.tsx
>      })
Como dijiste antes, estaría bueno que estén todas las imágenes en `imagePaths` con los paths full, sin necesidad de que el sketch maneje el `assetSource`.

2020-09-10 19:50 UTC, PalumboN commented on src/components/game/Sketch.tsx
> +  }
Excelente! :+1:

2020-09-11 20:33 UTC, tfloxolodeiro commented on src/components/game/Sketch.tsx
>      })
Ahi pushie una solucion para esto. Hice la funcion `defaultImagesNeededFor(imagePaths: string[]): string[]` por el caso de que haya una imagen del game que tenga el mismo nombre que alguna imagen default, asi solo se ponen en el `imagePaths` las imágenes default que "faltan" o se "necesitan". Tal vez el nombre de la función se podría mejorar, porque no necesariamente realmente se "necesitan" todas las imágenes default.

2020-09-12 09:30 UTC, PalumboN approved these changes
:muscle: :confused: :chart_with_upwards_trend:

2020-09-12 09:30 UTC, merged